"""Tests for `ol doctor` — the config validation checklist (OL#92).

Contract (scenarios 4-7):
4. `ol doctor --config <valid>` on a valid config (generated by `ol init`)
   → exit 0, output contains "[PASS]" and all 5 checks.
5. `ol doctor` on a config where a role has only 1 model → exit
   ExitCode.PIPELINE_ERROR, output contains "[FAIL]" AND the
   "run 'ol init'" hint.
6. `ol doctor` on a valid pool but a referenced ${VAR} is unset
   (ARK_API_KEY deleted + .env auto-load neutralized) → exit 1,
   "[FAIL]" for the env check.
7. `--json` emits ONE parseable object {"ok": bool, "checks": {5 keys}}.
8. `doctor` appears in `ol --help` output.
"""
from __future__ import annotations

import json

from typer.testing import CliRunner

from cli._shared import ExitCode
from ol_cli import app

runner = CliRunner()

ENV = {"OMNI_TEST_FAKE_LLM": "1"}

# Human-readable checklist names (must match src/cli/doctor.py display).
CHECK_NAMES = (
    "config file exists",
    "yaml parses",
    "load_config succeeds",
    "min models per role",
    "env vars resolve",
)

# Machine-readable JSON keys (must match src/cli/doctor.py --json).
JSON_KEYS = (
    "config_file_exists",
    "yaml_parses",
    "load_config_succeeds",
    "min_models_per_role",
    "env_vars_resolve",
)

# A config whose translation role has only 1 model → schema ValueError
# (check_min_models_per_role requires >=2). Other roles have 2 each so
# the failure is isolated to the translation role.
ONE_MODEL_ROLE_YAML = """\
project_id: test
source_lang: en
target_lang: zh
llm_pool:
  translation:
    - provider: openai
      model: ark-code-latest
      priority: 1
      role: translation
      api_key: "${ARK_API_KEY}"
      base_url: "https://ark.cn-beijing.volces.com/api/coding/v3"
  judging:
    - provider: openai
      model: ark-code-latest
      priority: 1
      role: judging
      api_key: "${ARK_API_KEY}"
      base_url: "https://ark.cn-beijing.volces.com/api/coding/v3"
    - provider: openai
      model: glm-4.7-flash
      priority: 2
      role: judging
      api_key: "${ZHIPU_API_KEY}"
      base_url: "https://open.bigmodel.cn/api/paas/v4"
  restoration:
    - provider: openai
      model: ark-code-latest
      priority: 1
      role: restoration
      api_key: "${ARK_API_KEY}"
      base_url: "https://ark.cn-beijing.volces.com/api/coding/v3"
    - provider: openai
      model: glm-4.7-flash
      priority: 2
      role: restoration
      api_key: "${ZHIPU_API_KEY}"
      base_url: "https://open.bigmodel.cn/api/paas/v4"
"""


def _write_valid_config(tmp_path):
    """Generate a valid config via `ol init` (the real bootstrap path)."""
    cfg = tmp_path / "local.yaml"
    result = runner.invoke(
        app,
        ["init", "--non-interactive", "--force", "--config", str(cfg)],
        env=ENV,
    )
    assert result.exit_code == 0, (
        f"init failed: exit={result.exit_code}, out={result.output!r}"
    )
    return cfg


def test_doctor_pass_valid_config(tmp_path):
    """Scenario 4: valid config → exit 0, [PASS] on all 5 checks."""
    cfg = _write_valid_config(tmp_path)
    result = runner.invoke(app, ["doctor", "--config", str(cfg)], env=ENV)
    assert result.exit_code == 0, (
        f"exit={result.exit_code}, out={result.output!r}, exc={result.exception!r}"
    )
    assert "[PASS]" in result.output
    for name in CHECK_NAMES:
        assert name in result.output, f"check {name!r} missing from output"


def test_doctor_fail_one_model_role(tmp_path):
    """Scenario 5: 1-model translation role → exit 1, [FAIL] + 'run ol init' hint."""
    cfg = tmp_path / "local.yaml"
    cfg.write_text(ONE_MODEL_ROLE_YAML, encoding="utf-8")

    result = runner.invoke(app, ["doctor", "--config", str(cfg)], env=ENV)
    assert result.exit_code == ExitCode.PIPELINE_ERROR, (
        f"exit={result.exit_code}, out={result.output!r}"
    )
    assert "[FAIL]" in result.output
    assert "run 'ol init'" in result.output


def test_doctor_fail_missing_env_var(tmp_path, monkeypatch):
    """Scenario 6: valid pool but ${ARK_API_KEY} unset → exit 1, env check FAIL."""
    cfg = _write_valid_config(tmp_path)

    # Neutralize loader._load_env_file: it loads Omni_Localizer/.env via a
    # FIXED path (loader.py:62-69) — NOT OL_DOTENV, NOT cwd — and would
    # re-introduce ARK_API_KEY via os.environ.setdefault. Patch it out.
    import ol_config.loader as loader_mod

    monkeypatch.setattr(loader_mod, "_load_env_file", lambda: None)
    monkeypatch.delenv("ARK_API_KEY", raising=False)

    result = runner.invoke(app, ["doctor", "--config", str(cfg)], env=ENV)
    assert result.exit_code == ExitCode.PIPELINE_ERROR, (
        f"exit={result.exit_code}, out={result.output!r}"
    )
    assert "[FAIL]" in result.output
    assert "env vars resolve" in result.output


def test_doctor_json_output(tmp_path):
    """Scenario 7: --json emits one parseable object with ok + 5 check keys."""
    cfg = _write_valid_config(tmp_path)
    result = runner.invoke(app, ["doctor", "--config", str(cfg), "--json"], env=ENV)
    assert result.exit_code == 0, (
        f"exit={result.exit_code}, out={result.output!r}, exc={result.exception!r}"
    )
    payload = json.loads(result.output)
    assert payload["ok"] is True
    assert set(payload["checks"].keys()) == set(JSON_KEYS)
    assert all(payload["checks"].values())


def test_doctor_in_help():
    """Scenario 8: `doctor` is registered and shows in `ol --help`."""
    result = runner.invoke(app, ["--help"], env=ENV)
    assert result.exit_code == 0
    assert "doctor" in result.output
